### PR TITLE
adding my background information

### PR DESCRIPTION
**Pull request by kpham7utk**

### CODE REVIEW

**Comment by kpham7utk** [comment]
https://github.com/kpham7utk/students

**Comment by adam-mcdaniel** [comment]
Use markdown syntax for hyperlink!

**Comment by kpham7utk** [comment]
Thanks, updated that.

**Comment by adam-mcdaniel** [comment]
Hmm I don't see any changes; did you push your commits?

**Comment by kpham7utk** [comment]
Sorry, I thought you meant I should change my earlier comment of the forked repository to markdown format. I used markdown syntax for my hyperlink.

**Pull request merged**
